(cluster/kcm) : created / updated KubeAid config files

diff --git a/k8s/kcm/argocd-apps/values-capi-cluster.yaml b/k8s/kcm/argocd-apps/values-capi-cluster.yaml
--- a/k8s/kcm/argocd-apps/values-capi-cluster.yaml
+++ b/k8s/kcm/argocd-apps/values-capi-cluster.yaml
@@ -21,10 +21,11 @@ hetzner:
     installImage:
       imagePath: /root/.oldroot/nfs/images/Ubuntu-2404-noble-amd64-base.tar.gz
     vg0: 
-      size: 50G
-      rootVolumeSize: 30G
+      size: 25G
+      rootVolumeSize: 10G
     diskLayoutSetupCommands: |
       
+      set -e
       apt-get update -y
       apt install zfsutils-linux -y
       
@@ -38,14 +39,20 @@ hetzner:
         #
         # A ZFS volume is a dataset that represents a block device. ZFS volumes are identified as
         # devices in the /dev/zvol/{dsk,rdsk}/pool directory.
-        zfs create -V 100G primary/containerd
+        zfs create -s -V 100G primary/containerd
         udevadm settle
         mkfs.ext4 /dev/zvol/primary/containerd
       
         # From that ZPool, set aside 50GB for ephemeral volumes for pods, by creating a ZVolume.
-        zfs create -V 50G primary/pod-ephemeral-volumes
+        zfs create -s -V 50G primary/pod-ephemeral-volumes
         udevadm settle
         mkfs.ext4 /dev/zvol/primary/pod-ephemeral-volumes
+      
+        # From that ZPool, set aside 50GB for pod logs, by creating a (thinly provisioned)
+        # ZVolume.
+        zfs create -s -V 50G primary/pod-logs
+        udevadm settle
+        mkfs.ext4 /dev/zvol/primary/pod-logs
       fi
       
       mkdir -p /var/lib/containerd
@@ -55,6 +62,15 @@ hetzner:
       mkdir -p /var/lib/kubelet/pods
       echo "/dev/zvol/primary/pod-ephemeral-volumes /var/lib/kubelet/pods ext4 defaults,nofail 0 0" | tee -a /etc/fstab
       mount /dev/zvol/primary/pod-ephemeral-volumes /var/lib/kubelet/pods
+      
+      mkdir -p /var/log
+      echo "/dev/zvol/primary/pod-logs /var/log ext4 defaults,nofail 0 0" | tee -a /etc/fstab
+      mount /dev/zvol/primary/pod-logs /var/log
+      
+      # Enable weekly ZPool trimming for the ZPool.
+      # So unused storage space will be reclaimed back, from the ZVolumes into the ZPool.
+      # REFER : https://openzfs.github.io/openzfs-docs/man/master/8/zpool-trim.8.html.
+      systemctl enable zfs-trim-weekly@rpool.timer --now
       
       # Create partition (without RAID) for Rook Ceph, which will take up the remaining of each HDD.
       echo ",,83" | sfdisk -N 4 /dev/sda --force
