(cluster/kcm) : created / updated KubeAid config files

diff --git a/k8s/kcm/argocd-apps/values-capi-cluster.yaml b/k8s/kcm/argocd-apps/values-capi-cluster.yaml
--- a/k8s/kcm/argocd-apps/values-capi-cluster.yaml
+++ b/k8s/kcm/argocd-apps/values-capi-cluster.yaml
@@ -109,4 +109,163 @@ hetzner:
 
   nodeGroups: 
     hcloud: []
-    bareMetal: []
+    bareMetal:
+      - name: zfs-and-ceph
+        labels:
+          node-role.kubernetes.io/zfs-and-ceph: ""
+          node.cluster.x-k8s.io/nodegroup: zfs-and-ceph
+        taints: []
+        bareMetalHosts:
+          - serverID: "2852588"
+            wwns:
+              - eui.343339304e4026070025384100000002
+              - eui.343339304e4026020025384100000002
+          - serverID: "2854796"
+            wwns:
+              - eui.343339304e5042380025384100000008
+              - eui.343339304e5042300025384100000008
+        diskLayoutSetupCommands: |
+          set -e
+    
+          apt-get update -y
+          apt install zfsutils-linux -y
+    
+          # In NVMe disk nvme0n1, create the nvme0n1p4 extended partition.
+          echo ",,E" | sfdisk -N 4 /dev/nvme0n1 --force --no-reread
+    
+          # And inside that extended partition, create nvme0n1p5 and nvme0n1p6 logical partitions,
+          # each taking up 50% of the extended partition.
+          # nvme0n1p5 : will be used by the primary ZFS pool.
+          # nvme0n1p6 : will be used by Rook Ceph.
+    
+          EXTENDED_PARTITION_SIZE=$(sfdisk -l /dev/nvme0n1 | grep nvme0n1p4 | awk '{print $4}')
+          EXTENDED_PARTITION_HALF_SIZE=$((EXTENDED_PARTITION_SIZE / 2))
+    
+          echo ",${EXTENDED_PARTITION_HALF_SIZE},83" | sfdisk -N 5 /dev/nvme0n1 --force --no-reread
+          echo ",,83" | sfdisk -N 6 /dev/nvme0n1 --force --no-reread
+    
+          partprobe /dev/nvme0n1
+          udevadm settle
+    
+          # Now, let's do the same for the NVMe disk nvme1n1.
+    
+          echo ",,E" | sfdisk -N 4 /dev/nvme1n1 --force --no-reread
+    
+          EXTENDED_PARTITION_SIZE=$(sfdisk -l /dev/nvme1n1 | grep nvme1n1p4 | awk '{print $4}')
+          EXTENDED_PARTITION_HALF_SIZE=$((EXTENDED_PARTITION_SIZE / 2))
+    
+          echo ",${EXTENDED_PARTITION_HALF_SIZE},83" | sfdisk -N 5 /dev/nvme1n1 --force --no-reread
+          echo ",,83" | sfdisk -N 6 /dev/nvme1n1 --force --no-reread
+    
+          partprobe /dev/nvme1n1
+          udevadm settle
+    
+          if zpool import -f primary >/dev/null 2>&1; then
+            echo "Imported existing primary ZPool"
+          else
+            # Create the mirrored ZPool out partitions : nvme0n1p5 and nvme1n1p5.
+            zpool create primary mirror /dev/nvme0n1p5 /dev/nvme1n1p5
+    
+            # From that ZPool, set aside 50GB for ContainerD, by creating a ZVolume.
+            #
+            # A ZFS volume is a dataset that represents a block device. ZFS volumes are identified as
+            # devices in the /dev/zvol/{dsk,rdsk}/pool directory.
+            zfs create -s -V 50G primary/containerd
+            udevadm settle
+            mkfs.ext4 /dev/zvol/primary/containerd
+    
+            # From that ZPool, set aside 50GB for ephemeral volumes for pods, by creating a ZVolume.
+            zfs create -s -V 50G primary/pod-ephemeral-volumes
+            udevadm settle
+            mkfs.ext4 /dev/zvol/primary/pod-ephemeral-volumes
+    
+            # From that ZPool, set aside 50GB for pod logs, by creating a (thinly provisioned)
+            # ZVolume.
+            zfs create -s -V 50G primary/pod-logs
+            udevadm settle
+            mkfs.ext4 /dev/zvol/primary/pod-logs
+          fi
+    
+          mkdir -p /var/lib/containerd
+          echo "/dev/zvol/primary/containerd /var/lib/containerd ext4 defaults,nofail 0 0" | tee -a /etc/fstab
+          mount /dev/zvol/primary/containerd /var/lib/containerd
+    
+          mkdir -p /var/lib/kubelet/pods
+          echo "/dev/zvol/primary/pod-ephemeral-volumes /var/lib/kubelet/pods ext4 defaults,nofail 0 0" | tee -a /etc/fstab
+          mount /dev/zvol/primary/pod-ephemeral-volumes /var/lib/kubelet/pods
+    
+          mkdir -p /var/log/pods
+          echo "/dev/zvol/primary/pod-logs /var/log/pods ext4 defaults,nofail 0 0" | tee -a /etc/fstab
+          mount /dev/zvol/primary/pod-logs /var/log/pods
+    
+          # Enable weekly ZPool trimming for the ZPool.
+          # So unused storage space will be reclaimed back, from the ZVolumes into the ZPool.
+          # REFER : https://openzfs.github.io/openzfs-docs/man/master/8/zpool-trim.8.html.
+          systemctl enable zfs-trim-weekly@rpool.timer --now
+      - name: zfs
+        labels:
+          node-role.kubernetes.io/zfs: ""
+          node.cluster.x-k8s.io/nodegroup: zfs
+        taints: []
+        bareMetalHosts:
+          - serverID: "2853926"
+            wwns:
+              - eui.0025388511c5b3e1
+              - eui.0025388511c5b367
+        diskLayoutSetupCommands: |
+          set -e
+    
+          apt-get update -y
+          apt install zfsutils-linux -y
+    
+          # In each NVMe disk, create a partition which'll take up the remaining storage space.
+          echo ",,83" | sfdisk -N 4 /dev/nvme0n1 --force
+          partprobe /dev/nvme0n1
+          echo ",,83" | sfdisk -N 4 /dev/nvme1n1 --force
+          partprobe /dev/nvme1n1
+          udevadm settle
+    
+          if zpool import -f primary >/dev/null 2>&1; then
+            echo "Imported existing primary ZPool"
+          else
+            # Create a mirrored ZPool out of those 2 partitions.
+            zpool create primary mirror /dev/nvme0n1p4 /dev/nvme1n1p4
+    
+            # From that ZPool, set aside 50GB for ContainerD, by creating a (thinly provisioned)
+            # ZVolume.
+            #
+            # A ZFS volume is a dataset that represents a block device. ZFS volumes are identified
+            # as devices in the /dev/zvol/{dsk,rdsk}/pool directory.
+            zfs create -s -V 50G primary/containerd
+            udevadm settle
+            mkfs.ext4 /dev/zvol/primary/containerd
+    
+            # From that ZPool, set aside 50GB for ephemeral volumes for pods, by creating a
+            # (thinly provisioned) ZVolume.
+            zfs create -s -V 50G primary/pod-ephemeral-volumes
+            udevadm settle
+            mkfs.ext4 /dev/zvol/primary/pod-ephemeral-volumes
+    
+            # From that ZPool, set aside 50GB for pod logs, by creating a (thinly provisioned)
+            # ZVolume.
+            zfs create -s -V 50G primary/pod-logs
+            udevadm settle
+            mkfs.ext4 /dev/zvol/primary/pod-logs
+          fi
+    
+          mkdir -p /var/lib/containerd
+          echo "/dev/zvol/primary/containerd /var/lib/containerd ext4 defaults,nofail 0 0" | tee -a /etc/fstab
+          mount /dev/zvol/primary/containerd /var/lib/containerd
+    
+          mkdir -p /var/lib/kubelet/pods
+          echo "/dev/zvol/primary/pod-ephemeral-volumes /var/lib/kubelet/pods ext4 defaults,nofail 0 0" | tee -a /etc/fstab
+          mount /dev/zvol/primary/pod-ephemeral-volumes /var/lib/kubelet/pods
+    
+          mkdir -p /var/log/pods
+          echo "/dev/zvol/primary/pod-logs /var/log/pods ext4 defaults,nofail 0 0" | tee -a /etc/fstab
+          mount /dev/zvol/primary/pod-logs /var/log/pods
+    
+          # Enable weekly ZPool trimming for the ZPool.
+          # So unused storage space will be reclaimed back, from the ZVolumes into the ZPool.
+          # REFER : https://openzfs.github.io/openzfs-docs/man/master/8/zpool-trim.8.html.
+          systemctl enable zfs-trim-weekly@rpool.timer --now
